FROM python:3.10-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY . /home/test/PycharmProjects/pythonProject123/mysite
WORKDIR /home/test/PycharmProjects/pythonProject123/mysite

RUN pip install --upgrade pip && pip install -r requirements.txt

CMD python mysite/te.py
